# Generated by Django 4.1.4 on 2022-12-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thelab', '0003_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='absence_type',
            field=models.CharField(choices=[('Home Office', 'HO'), ('Office', 'O')], default='HO', max_length=200),
            preserve_default=False,
        ),
    ]
